### ISSUE TITLE
Are you still maintaining this project?

### ISSUE THREAD

**Issue by moklick** [cruzrr/node-weedfs#19]
I was wondering if you are still maintaining this project?

**Comment by phal0r** [comment]
Hi, i have refactored this lib in my fork. Maybe you want to have a look: https://github.com/atroo/node-weedfs

**Comment by moklick** [comment]
Hey. Thanks :+1:  I will check that

**Comment by ablakely** [comment]
What are you looking for?

It's still functioning, and yes when something breaks it will be fixed.  Although, I'm not currently using it in any of my programs right now.
