### ISSUE TITLE
Safe for node cluster usage?

### ISSUE THREAD

**Issue by markschmid** [cruzrr/node-weedfs#21]
Does anyone know if this library is suitable for multi-process access?
Can it be safely shared between multiple Node processes (Node cluster)?

**Comment by ablakely** [comment]
I don't see why it wouldn't be.

Would all of them be creating their own instances?

**Comment by markschmid** [comment]
Thanks for your response. Yes, every instance would create a "new weedClient()"
The question was only to make sure. There are libraries that explicitly can't be used in a cluster environment, e.g. https://github.com/Level/levelup#multi-process-access

**Comment by ablakely** [comment]
Then it should work fine.
